In [54]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

In [55]:
classifier = Sequential()

In [56]:
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

In [57]:
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [58]:
classifier.add(Flatten())

In [59]:
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 10, activation = 'softmax'))

In [60]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [61]:
from keras.preprocessing.image import ImageDataGenerator

In [62]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)


In [63]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [64]:
training_set = train_datagen.flow_from_directory('train',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

Found 17000 images belonging to 10 classes.


In [65]:
test_set = test_datagen.flow_from_directory('test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 3000 images belonging to 10 classes.


In [66]:
classifier.fit_generator(training_set,
                         steps_per_epoch = 17000,
                         epochs = 2,
                         validation_data = test_set,
                         validation_steps = 3000)

Epoch 1/2
17000/17000 [==============================] - 6313s - loss: 0.0818 - acc: 0.9729 - val_loss: 0.0636 - val_acc: 0.9817
Epoch 2/2
17000/17000 [==============================] - 6180s - loss: 0.0237 - acc: 0.9922 - val_loss: 0.0586 - val_acc: 0.9863


In [67]:
import numpy as np
from keras.preprocessing import image

In [71]:
individual_image=image.load_img('second.png', target_size = (64, 64))
individual_image = image.img_to_array(individual_image)
individual_image = np.expand_dims(individual_image, axis = 0)
result = classifier.predict(individual_image)

In [72]:
result

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [73]:
training_set.class_indices

{'digit_0': 0,
 'digit_1': 1,
 'digit_2': 2,
 'digit_3': 3,
 'digit_4': 4,
 'digit_5': 5,
 'digit_6': 6,
 'digit_7': 7,
 'digit_8': 8,
 'digit_9': 9}

In [74]:
individual_image=image.load_img('image.jpg', target_size = (64, 64))
individual_image = image.img_to_array(individual_image)
individual_image = np.expand_dims(individual_image, axis = 0)
result = classifier.predict(individual_image)

In [75]:
result

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [76]:
individual_image=image.load_img('first.png', target_size = (64, 64))
individual_image = image.img_to_array(individual_image)
individual_image = np.expand_dims(individual_image, axis = 0)
result = classifier.predict(individual_image)

In [77]:
result

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)